#include "pch.h"
#include "Microsoft.Xbox.Services.TitleStorage.TitleStorageBlobMetadata.h"
#include "Microsoft.Xbox.Services.TitleStorage.TitleStorageBlobMetadata.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::TitleStorage::implementation
{
    TitleStorageBlobMetadata::TitleStorageBlobMetadata(hstring const& serviceConfigurationId, winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageType const& storageType, hstring const& blobPath, winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageBlobType const& blobType, hstring const& xboxUserId)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    TitleStorageBlobMetadata::TitleStorageBlobMetadata(hstring const& serviceConfigurationId, winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageType const& storageType, hstring const& blobPath, winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageBlobType const& blobType, hstring const& xboxUserId, hstring const& displayName, hstring const& eTag)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    TitleStorageBlobMetadata::TitleStorageBlobMetadata(hstring const& serviceConfigurationId, winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageType const& storageType, hstring const& blobPath, winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageBlobType const& blobType, hstring const& xboxUserId, hstring const& displayName, hstring const& eTag, winrt::Windows::Foundation::DateTime const& clientTimestamp)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageBlobMetadata TitleStorageBlobMetadata::CreateTitleStorageBlobMetadataForSessionStorage(hstring const& serviceConfigurationId, hstring const& blobPath, winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageBlobType const& blobType, hstring const& multiplayerSessionTemplateName, hstring const& multiplayerSessionName, hstring const& displayName, hstring const& eTag)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring TitleStorageBlobMetadata::BlobPath()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageBlobType TitleStorageBlobMetadata::BlobType()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageType TitleStorageBlobMetadata::StorageType()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring TitleStorageBlobMetadata::DisplayName()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring TitleStorageBlobMetadata::ETag()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime TitleStorageBlobMetadata::ClientTimestamp()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void TitleStorageBlobMetadata::set(winrt::Windows::Foundation::DateTime const& value)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint64_t TitleStorageBlobMetadata::Length()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring TitleStorageBlobMetadata::ServiceConfigurationId()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring TitleStorageBlobMetadata::XboxUserId()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring TitleStorageBlobMetadata::MultiplayerSessionTemplateName()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring TitleStorageBlobMetadata::MultiplayerSessionName()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
