#include "pch.h"
#include "Microsoft.Xbox.Services.Social.SocialService.h"
#include "Microsoft.Xbox.Services.Social.SocialService.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Social::implementation
{
    winrt::event_token SocialService::SocialRelationshipChanged(winrt::Windows::Foundation::EventHandler<winrt::Microsoft::Xbox::Services::Social::SocialRelationshipChangeEventArgs> const& __param0)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void SocialService::SocialRelationshipChanged(winrt::event_token const& __param0) noexcept
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Social::XboxSocialRelationshipResult> SocialService::GetSocialRelationshipsAsync()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Social::XboxSocialRelationshipResult> SocialService::GetSocialRelationshipsAsync(winrt::Microsoft::Xbox::Services::Social::SocialRelationship socialRelationshipFilter)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Social::XboxSocialRelationshipResult> SocialService::GetSocialRelationshipsAsync(hstring xboxUserId)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Social::XboxSocialRelationshipResult> SocialService::GetSocialRelationshipsAsync(winrt::Microsoft::Xbox::Services::Social::SocialRelationship socialRelationshipFilter, uint32_t startIndex, uint32_t maxItems)
    {
        co_await winrt::resume_background( );
    }
    winrt::Microsoft::Xbox::Services::Social::SocialRelationshipChangeSubscription SocialService::SubscribeToSocialRelationshipChange(hstring const& xboxUserId)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void SocialService::UnsubscribeFromSocialRelationshipChange(winrt::Microsoft::Xbox::Services::Social::SocialRelationshipChangeSubscription const& subscription)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
