#include "pch.h"
#include "Microsoft.Xbox.Services.Privacy.PermissionIdConstants.h"
#include "Microsoft.Xbox.Services.Privacy.PermissionIdConstants.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Privacy::implementation
{
    hstring PermissionIdConstants::CommunicateUsingText()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::CommunicateUsingVideo()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::CommunicateUsingVoice()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetProfile()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetGameHistory()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetVideoHistory()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetMusicHistory()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetExerciseInfo()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetPresence()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetVideoStatus()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetMusicStatus()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::PlayMultiplayer()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::BroadcastWithTwitch()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring PermissionIdConstants::ViewTargetUserCreatedContent()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
