#include "pch.h"
#include "Microsoft.Xbox.GameChat.ChatUser.h"
#include "Microsoft.Xbox.GameChat.ChatUser.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::GameChat::implementation
{
    hstring ChatUser::XboxUserId()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IInspectable ChatUser::UniqueConsoleIdentifier()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::GameChat::ChatUserTalkingMode ChatUser::TalkingMode()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint32_t ChatUser::NumberOfPendingAudioPacketsToPlay()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint32_t ChatUser::DynamicNeededPacketCount()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Chat::ChatRestriction ChatUser::RestrictionMode()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::System::IUser ChatUser::User()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool ChatUser::IsLocal()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool ChatUser::IsLocalUserMuted()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool ChatUser::IsMuted()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<uint8_t> ChatUser::GetAllChannels()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void ChatUser::GenerateTextMessage(hstring const& message, bool allowTextToSpeechConversion)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Chat::ChatParticipantTypes ChatUser::ParticipantType()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void ChatUser::ParticipantType(winrt::Windows::Xbox::Chat::ChatParticipantTypes const& val)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    float ChatUser::Volume()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void ChatUser::Volume(float val)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    float ChatUser::LocalRenderTargetVolume()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void ChatUser::LocalRenderTargetVolume(float val)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool ChatUser::HasRequestedTranscription()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool ChatUser::HasRequestedSynthesizedAudio()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
