#include "pch.h"
#include "Microsoft.Xbox.Services.System.XboxLiveServicesSettings.h"
#include "Microsoft.Xbox.Services.System.XboxLiveServicesSettings.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::System::implementation
{
    winrt::Microsoft::Xbox::Services::System::XboxLiveServicesSettings XboxLiveServicesSettings::SingletonInstance()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::event_token XboxLiveServicesSettings::LogCallRouted(winrt::Windows::Foundation::EventHandler<winrt::Microsoft::Xbox::Services::XboxLiveLogCallEventArgs> const& __param0)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void XboxLiveServicesSettings::LogCallRouted(winrt::event_token const& __param0) noexcept
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::XboxServicesDiagnosticsTraceLevel XboxLiveServicesSettings::DiagnosticsTraceLevel()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void XboxLiveServicesSettings::DiagnosticsTraceLevel(winrt::Microsoft::Xbox::Services::XboxServicesDiagnosticsTraceLevel const& value)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::event_token XboxLiveServicesSettings::WnsEventRecevied(winrt::Windows::Foundation::EventHandler<winrt::Microsoft::Xbox::Services::XboxLiveWnsEventArgs> const& __param0)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void XboxLiveServicesSettings::WnsEventRecevied(winrt::event_token const& __param0) noexcept
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
