#include "pch.h"
#include "Microsoft.Xbox.Services.Marketplace.CatalogItemDetails.h"
#include "Microsoft.Xbox.Services.Marketplace.CatalogItemDetails.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Marketplace::implementation
{
    winrt::Microsoft::Xbox::Services::Marketplace::MediaItemType CatalogItemDetails::MediaItemType()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring CatalogItemDetails::Id()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring CatalogItemDetails::Name()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring CatalogItemDetails::ReducedName()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring CatalogItemDetails::Description()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint32_t CatalogItemDetails::TitleId()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime CatalogItemDetails::ReleaseDate()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring CatalogItemDetails::ProductId()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring CatalogItemDetails::SandboxId()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool CatalogItemDetails::IsBundle()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool CatalogItemDetails::IsPartOfAnyBundle()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Marketplace::CatalogItemImage> CatalogItemDetails::Images()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Marketplace::CatalogItemAvailability> CatalogItemDetails::Availabilities()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
