#include "pch.h"
#include "Microsoft.Xbox.Services.Tournaments.Tournament.h"
#include "Microsoft.Xbox.Services.Tournaments.Tournament.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Tournaments::implementation
{
    hstring Tournament::Id()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring Tournament::OrganizerId()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring Tournament::OrganizerName()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring Tournament::Name()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring Tournament::Description()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring Tournament::GameMode()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    hstring Tournament::TournamentStyle()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool Tournament::IsRegistrationOpen()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool Tournament::IsCheckinOpen()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool Tournament::IsPlayingOpen()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool Tournament::HasPrize()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    bool Tournament::IsPaused()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint32_t Tournament::MinTeamSize()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint32_t Tournament::MaxTeamSize()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint32_t Tournament::TeamsRegisteredCount()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint32_t Tournament::MinTeamsRegistered()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint32_t Tournament::MaxTeamsRegistered()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Tournaments::TournamentState Tournament::TournamentState()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime Tournament::RegistrationStartTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime Tournament::RegistrationEndTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime Tournament::CheckinStartTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime Tournament::CheckinEndTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime Tournament::PlayingStartTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime Tournament::PlayingEndTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::DateTime Tournament::EndTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Tournaments::TeamSummary Tournament::TeamSummary()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
