#include "pch.h"
#include "Microsoft.Xbox.Services.Matchmaking.MatchmakingService.h"
#include "Microsoft.Xbox.Services.Matchmaking.MatchmakingService.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Matchmaking::implementation
{
    winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Matchmaking::CreateMatchTicketResponse> MatchmakingService::CreateMatchTicketAsync(winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionReference ticketSessionReference, hstring matchmakingServiceConfigurationId, hstring hopperName, winrt::Windows::Foundation::TimeSpan ticketTimeout, winrt::Microsoft::Xbox::Services::Matchmaking::PreserveSessionMode preserveSession, hstring ticketAttributesJson)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncAction MatchmakingService::DeleteMatchTicketAsync(hstring serviceConfigurationId, hstring hopperName, hstring ticketId)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Matchmaking::MatchTicketDetailsResponse> MatchmakingService::GetMatchTicketDetailsAsync(hstring serviceConfigurationId, hstring hopperName, hstring ticketId)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Matchmaking::HopperStatisticsResponse> MatchmakingService::GetHopperStatisticsAsync(hstring serviceConfigurationId, hstring hopperName)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
