#include "pch.h"
#include "Windows.Kinect.DepthFrame.h"
#include "Windows.Kinect.DepthFrame.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Kinect::implementation
{
    void DepthFrame::Close()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void DepthFrame::CopyFrameDataToArray(array_view<uint16_t> frameData)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void DepthFrame::CopyFrameDataToBuffer(winrt::Windows::Storage::Streams::IBuffer const& buffer)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Storage::Streams::IBuffer DepthFrame::LockImageBuffer()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Kinect::FrameDescription DepthFrame::FrameDescription()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::TimeSpan DepthFrame::RelativeTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Kinect::DepthFrameSource DepthFrame::DepthFrameSource()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint16_t DepthFrame::DepthMinReliableDistance()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    uint16_t DepthFrame::DepthMaxReliableDistance()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
