#include "pch.h"
#include "Windows.Kinect.AudioBeam.h"
#include "Windows.Kinect.AudioBeam.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Kinect::implementation
{
    winrt::Windows::Kinect::AudioSource AudioBeam::AudioSource()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Kinect::AudioBeamMode AudioBeam::AudioBeamMode()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void AudioBeam::AudioBeamMode(winrt::Windows::Kinect::AudioBeamMode const& audioBeamMode)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    float AudioBeam::BeamAngle()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    void AudioBeam::BeamAngle(float beamAngle)
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    float AudioBeam::BeamAngleConfidence()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::TimeSpan AudioBeam::RelativeTime()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
    winrt::Windows::Storage::Streams::IInputStream AudioBeam::OpenInputStream()
    {
        printf("%s called\n", __FUNCTION__); throw hresult_not_implemented();
    }
}
