#pragma once
#include "Windows.Xbox.Networking.SecureDeviceAssociation.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::Networking::implementation
{
    struct SecureDeviceAssociation : SecureDeviceAssociationT<SecureDeviceAssociation>
    {
        SecureDeviceAssociation() = default;

        static winrt::Windows::Xbox::Networking::SecureDeviceAssociation GetAssociationBySocketAddressBytes(array_view<uint8_t const> remoteSocketAddressBytes, array_view<uint8_t const> localSocketAddressBytes);
        static winrt::Windows::Xbox::Networking::SecureDeviceAssociation GetAssociationByHostNamesAndPorts(winrt::Windows::Networking::HostName const& remoteHostName, hstring const& remotePort, winrt::Windows::Networking::HostName const& localHostName, hstring const& localPort);
        winrt::event_token StateChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Networking::SecureDeviceAssociation, winrt::Windows::Xbox::Networking::SecureDeviceAssociationStateChangedEventArgs> const& handler);
        void StateChanged(winrt::event_token const& token) noexcept;
        winrt::Windows::Foundation::IAsyncAction DestroyAsync();
        void GetRemoteSocketAddressBytes(array_view<uint8_t> socketAddressBytes);
        void GetLocalSocketAddressBytes(array_view<uint8_t> socketAddressBytes);
        winrt::Windows::Xbox::Networking::SecureDeviceAssociationState State();
        winrt::Windows::Xbox::Networking::SecureDeviceAssociationTemplate Template();
        winrt::Windows::Xbox::Networking::SecureDeviceAddress RemoteSecureDeviceAddress();
        winrt::Windows::Networking::HostName RemoteHostName();
        hstring RemotePort();
        winrt::Windows::Networking::HostName LocalHostName();
        hstring LocalPort();
    };
}
namespace winrt::Windows::Xbox::Networking::factory_implementation
{
    struct SecureDeviceAssociation : SecureDeviceAssociationT<SecureDeviceAssociation, implementation::SecureDeviceAssociation>
    {
    };
}
