#pragma once
#define D3D11X_RESOURCE_MISC_FORCE_TEXTURE_COMPATIBILITY D3D11_RESOURCE_MISC_FLAG(1 << 15)
#define D3D11X_RESOURCE_MISC_ESRAM_RESIDENT              D3D11_RESOURCE_MISC_FLAG(1 << 17)
#define D3D11X_RESOURCE_MISC_NO_COLOR_EXPAND             D3D11_RESOURCE_MISC_FLAG(1 << 18)
#define D3D11X_RESOURCE_MISC_NO_COLOR_COMPRESSION        D3D11_RESOURCE_MISC_FLAG(1 << 19)
#define D3D11X_RESOURCE_MISC_NO_DEPTH_COMPRESSION        D3D11_RESOURCE_MISC_FLAG(1 << 20)
#define D3D11X_RESOURCE_MISC_NO_STENCIL_COMPRESSION      D3D11_RESOURCE_MISC_FLAG(1 << 21)
#define D3D11X_RESOURCE_MISC_ALLOW_DCC                   D3D11_RESOURCE_MISC_FLAG(1 << 22)
#define D3D11X_RESOURCE_MISC_TILE_POOL                   D3D11_RESOURCE_MISC_FLAG(1 << 26) // conflict
#define D3D11X_RESOURCE_MISC_TILED                       D3D11_RESOURCE_MISC_FLAG(1 << 27) // conflict

#define D3D11X_RESOURCE_MISC_MASK                    ( \
    D3D11X_RESOURCE_MISC_FORCE_TEXTURE_COMPATIBILITY | \
    D3D11X_RESOURCE_MISC_ESRAM_RESIDENT              | \
    D3D11X_RESOURCE_MISC_NO_COLOR_EXPAND             | \
    D3D11X_RESOURCE_MISC_NO_COLOR_COMPRESSION        | \
    D3D11X_RESOURCE_MISC_NO_DEPTH_COMPRESSION        | \
    D3D11X_RESOURCE_MISC_NO_STENCIL_COMPRESSION      | \
    D3D11X_RESOURCE_MISC_ALLOW_DCC                   | \
    D3D11X_RESOURCE_MISC_TILE_POOL                   | \
    D3D11X_RESOURCE_MISC_TILED                       )

#define D3D11_RESOURCE_MISC_MASK                        ( \
    D3D11_RESOURCE_MISC_GENERATE_MIPS                   | \
    D3D11_RESOURCE_MISC_SHARED                          | \
    D3D11_RESOURCE_MISC_TEXTURECUBE                     | \
    D3D11_RESOURCE_MISC_DRAWINDIRECT_ARGS               | \
    D3D11_RESOURCE_MISC_BUFFER_ALLOW_RAW_VIEWS          | \
    D3D11_RESOURCE_MISC_BUFFER_STRUCTURED               | \
    D3D11_RESOURCE_MISC_RESOURCE_CLAMP                  | \
    D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX               | \
    D3D11_RESOURCE_MISC_GDI_COMPATIBLE                  | \
    D3D11_RESOURCE_MISC_SHARED_NTHANDLE                 | \
    D3D11_RESOURCE_MISC_RESTRICTED_CONTENT              | \
    D3D11_RESOURCE_MISC_RESTRICT_SHARED_RESOURCE        | \
    D3D11_RESOURCE_MISC_RESTRICT_SHARED_RESOURCE_DRIVER | \
    D3D11_RESOURCE_MISC_GUARDED                         | \
    D3D11_RESOURCE_MISC_TILE_POOL                       | \
    D3D11_RESOURCE_MISC_TILED                           | \
    D3D11_RESOURCE_MISC_HW_PROTECTED                    )